In [5]:
import pandas as pd

In [9]:
df = pd.read_csv('dados_comunidade.csv')

In [11]:
df = df.replace({'Sim': 1, 'Não': 0})

C:\Users\gabri\AppData\Local\Temp\ipykernel_30380\2398527104.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace({'Sim': 1, 'Não': 0})

In [14]:
df.head()

,Carimbo de data/hora,Como conheceu o Téo Me Why?,Quantos cursos acompanhou do Téo Me Why?,Curte games?,Curte futebol?,Curte livros?,Curte jogos de tabuleiro?,Curte jogos de fórmula 1?,Curte jogos de MMA?,Idade,Estado que mora atualmente,Área de Formação,Tempo que atua na área de dados,Posição da cadeira (senioridade),Você se considera uma pessoa feliz?
0,12/06/2025 10:59:27,LinkedIn,0,1,0,1,1,1,0,34,MG,Exatas,Mais de 4 anos,Sênior,1
1,12/06/2025 10:59:34,Twitch,Mais que 3,1,1,1,0,0,1,26,MG,Exatas,Não atuo,Iniciante,1
2,12/06/2025 10:59:36,YouTube,Mais que 3,1,1,1,1,1,1,39,SC,Exatas,De 1 ano a 2 anos,Júnior,1
3,12/06/2025 10:59:37,YouTube,Mais que 3,1,1,1,1,1,0,27,SP,Exatas,Mais de 4 anos,Pleno,1
4,12/06/2025 10:59:41,Twitch,2,1,1,1,1,0,0,29,CE,Exatas,De 1 ano a 2 anos,Pleno,1

In [25]:
num_vars =['Curte games?',	
'Curte futebol?',
'Curte livros?',	
'Curte jogos de tabuleiro?',
'Curte jogos de fórmula 1?',
'Curte jogos de MMA?',	
'Idade']

dummy_vars = ['Como conheceu o Téo Me Why?',
'Quantos cursos acompanhou do Téo Me Why?',
'Estado que mora atualmente',
'Área de Formação',
'Tempo que atua na área de dados',
'Posição da cadeira (senioridade)']
df_analise = pd.get_dummies(df[dummy_vars]).astype(int) # má prática!!
df_analise[num_vars] = df[num_vars].copy()
df_analise

,Como conheceu o Téo Me Why?_Amigos,Como conheceu o Téo Me Why?_Instagram,Como conheceu o Téo Me Why?_LinkedIn,Como conheceu o Téo Me Why?_Outra rede social,Como conheceu o Téo Me Why?_Twitch,Como conheceu o Téo Me Why?_Twitter / X,Como conheceu o Téo Me Why?_YouTube,Quantos cursos acompanhou do Téo Me Why?_0,Quantos cursos acompanhou do Téo Me Why?_1,Quantos cursos acompanhou do Téo Me Why?_2,...,Posição da cadeira (senioridade)_Júnior,Posição da cadeira (senioridade)_Pleno,Posição da cadeira (senioridade)_Sênior,Curte games?,Curte futebol?,Curte livros?,Curte jogos de tabuleiro?,Curte jogos de fórmula 1?,Curte jogos de MMA?,Idade
0,0,0,1,0,0,0,0,1,0,0,...,0,0,1,1,0,1,1,1,0,34
1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,1,1,1,0,0,1,26
2,0,0,0,0,0,0,1,0,0,0,...,1,0,0,1,1,1,1,1,1,39
3,0,0,0,0,0,0,1,0,0,0,...,0,1,0,1,1,1,1,1,0,27
4,0,0,0,0,1,0,0,0,0,1,...,0,1,0,1,1,1,1,0,0,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,1,0,0,0,0,0,0,0,0,1,...,1,0,0,1,1,1,0,1,0,33
178,0,0,0,0,1,0,0,0,0,0,...,0,0,1,1,1,1,1,1,1,32
179,0,0,0,0,0,1,0,0,1,0,...,0,0,0,1,1,1,1,0,0,39
180,0,0,1,0,0,0,0,0,1,0,...,0,1,0,1,0,1,0,0,0,25
181,0,0,0,0,0,0,1,0,1,0,...,0,0,0,1,0,1,1,0,0,43

In [37]:
df_analise['pessoa feliz'] = df['Você se considera uma pessoa feliz?'].copy()
df_analise

,Como conheceu o Téo Me Why?_Amigos,Como conheceu o Téo Me Why?_Instagram,Como conheceu o Téo Me Why?_LinkedIn,Como conheceu o Téo Me Why?_Outra rede social,Como conheceu o Téo Me Why?_Twitch,Como conheceu o Téo Me Why?_Twitter / X,Como conheceu o Téo Me Why?_YouTube,Quantos cursos acompanhou do Téo Me Why?_0,Quantos cursos acompanhou do Téo Me Why?_1,Quantos cursos acompanhou do Téo Me Why?_2,...,Posição da cadeira (senioridade)_Pleno,Posição da cadeira (senioridade)_Sênior,Curte games?,Curte futebol?,Curte livros?,Curte jogos de tabuleiro?,Curte jogos de fórmula 1?,Curte jogos de MMA?,Idade,pessoa feliz
0,0,0,1,0,0,0,0,1,0,0,...,0,1,1,0,1,1,1,0,34,1
1,0,0,0,0,1,0,0,0,0,0,...,0,0,1,1,1,0,0,1,26,1
2,0,0,0,0,0,0,1,0,0,0,...,0,0,1,1,1,1,1,1,39,1
3,0,0,0,0,0,0,1,0,0,0,...,1,0,1,1,1,1,1,0,27,1
4,0,0,0,0,1,0,0,0,0,1,...,1,0,1,1,1,1,0,0,29,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177,1,0,0,0,0,0,0,0,0,1,...,0,0,1,1,1,0,1,0,33,1
178,0,0,0,0,1,0,0,0,0,0,...,0,1,1,1,1,1,1,1,32,1
179,0,0,0,0,0,1,0,0,1,0,...,0,0,1,1,1,1,0,0,39,0
180,0,0,1,0,0,0,0,0,1,0,...,1,0,1,0,1,0,0,0,25,0
181,0,0,0,0,0,0,1,0,1,0,...,0,0,1,0,1,1,0,0,43,1

In [46]:
features = df_analise.columns[:-1].tolist()
X = df_analise[features]
y = df_analise['pessoa feliz']

In [39]:
from sklearn import tree

In [72]:
arvore = tree.DecisionTreeClassifier(random_state=42,
                                     min_samples_leaf=5,
                                    )

In [73]:
arvore.fit(X, y)

DecisionTreeClassifier(min_samples_leaf=5, random_state=42)

In [74]:
arvore_predict = arvore.predict(X) #Não se usa o mesmo dado para treinar e predictar
arvore_predict

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1])

In [75]:
df_predict = df_analise[['pessoa feliz']]
df_predict['predict_arvore'] = arvore_predict
df_predict

C:\Users\gabri\AppData\Local\Temp\ipykernel_30380\2371675727.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_predict['predict_arvore'] = arvore_predict

     pessoa feliz  predict_arvore
0               1               1
1               1               1
2               1               1
3               1               1
4               1               1
..            ...             ...
177             1               1
178             1               1
179             0               0
180             0               0
181             1               1

[182 rows x 2 columns]

In [77]:
# Acurácia! (as vezes não é suficiente -> não me fala onde estou acertando)
(df_predict['pessoa feliz'] == df_predict['predict_arvore']).mean()

np.float64(0.8626373626373627)

In [79]:
pd.crosstab(df_predict['pessoa feliz'], df_predict['predict_arvore'])

predict_arvore   0    1
pessoa feliz
0               16   19
1                6  141

dos 21 `zeros` que meu modelo disse que tinha ele acertou 16 e errou 6
essa é uma maneira de se interpretar essa pequena matriz de confusão

In [81]:
(df_predict['pessoa feliz'] == 1).sum()

np.int64(147)